services:
  - type: web
    name: journal-management-app
    env: java
    repo: https://github.com/yourusername/journal-management
    branch: main
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/journal-management-0.0.1-SNAPSHOT.jar
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
